

// import java.io.FileInputStream
// import java.util.Properties


// plugins {
//      id("com.android.application")
//      id("org.jetbrains.kotlin.android")
//      id("dev.flutter.flutter-gradle-plugin")
//      id("com.google.gms.google-services")
//  }

//  val localProperties = Properties()
//  val localPropertiesFile = rootProject.file("local.properties") if (localPropertiesFile.exists()) {
//      localPropertiesFile.inputStream().use { input ->
//          localProperties.load(input)
//      }
//  }

//  val flutterVersionCode: Int = localProperties.getProperty("flutter.versionCode")?.toInt() ?: 1
//  val flutterVersionName: String = localProperties.getProperty("flutter.versionName") ?: "1.0"

//  val keystoreProperties = Properties()
//  val keystorePropertiesFile = project.file("../key.properties")
//  var hasKeystore = false
//  if (keystorePropertiesFile.exists()) {
//      keystorePropertiesFile.inputStream().use { input ->
//          keystoreProperties.load(input)
//      }
//        hasKeystore = true
//  }
// //  println("DEBUG: keystorePropertiesFile = ${keystorePropertiesFile.absolutePath}  exists=${keystorePropertiesFile.exists()}")
// println("DEBUG: key.properties exists = $hasKeystore")

//  android {
//      namespace = "com.flutter.deligo_delivery"
//      compileSdk = 36
//      ndkVersion = "27.0.12077973"

//      compileOptions {
//          sourceCompatibility = JavaVersion.VERSION_11
//          targetCompatibility = JavaVersion.VERSION_11
//      }

//      kotlinOptions {
//          jvmTarget = JavaVersion.VERSION_11.toString()
//      }

//      defaultConfig {
//          applicationId = "com.flutter.deligo_delivery"
//          minSdk = flutter.minSdkVersion
//          targetSdk = 36
//          versionCode = flutterVersionCode
//          versionName = flutterVersionName
//      }

//      signingConfigs {
//         if (hasKeystore) {
//          create("release") {
//              keyAlias = keystoreProperties.getProperty("keyAlias")
//              keyPassword = keystoreProperties.getProperty("keyPassword")
//              storeFile = file(keystoreProperties.getProperty("storeFile")!!)
//              storePassword = keystoreProperties.getProperty("storePassword")
//          }
//      } 
//   }

//      buildTypes {
//     //  below code is checking if release keystore is present. - added by prateek - 03 dec 2025
//      release {

//              if (hasKeystore) {
//                  signingConfig = signingConfigs.getByName("release")
//              } else {
//                  println("WARNING: Using debug signing for release because key.properties is missing!")
//                  signingConfig = signingConfigs.getByName("debug")
//              }

//              // Enable if you want
//              // isMinifyEnabled = true
//              // isShrinkResources = true
//          }
//      }
//  }

//  flutter {
//      source = "../.."
//  }

//  // ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
//  apply { from("flavorizr.gradle.kts") }
//  // ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----

import java.io.FileInputStream
import java.util.Properties
 
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
}
 
 
val localProperties = Properties()
val localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.inputStream().use { input ->
        localProperties.load(input)
    }
}
 
val flutterVersionCode: Int = localProperties.getProperty("flutter.versionCode")?.toInt() ?: 1
val flutterVersionName: String = localProperties.getProperty("flutter.versionName") ?: "1.0"
 
// --------- SAFE KEYSTORE LOADING (OPTION-B) ----------
val keystoreProperties = Properties()
val keystorePropertiesFile = project.file("../key.properties")
var hasKeystore = false
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.inputStream().use { input ->
        keystoreProperties.load(input)
    }
    hasKeystore = true
}
 
println("DEBUG: key.properties exists = $hasKeystore")
// ----------------------------------------------------
 
android {
    namespace = "com.flutter.deligo_delivery"
    compileSdk = 36
    ndkVersion = "27.0.12077973"
 
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
 
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }
 
    defaultConfig {
        applicationId = "com.flutter.deligo_delivery"
        minSdk = flutter.minSdkVersion
        targetSdk = 36
        versionCode = flutterVersionCode
        versionName = flutterVersionName
 
        // Add these: Update by Prateek 
        manifestPlaceholders.putAll(
        mapOf(
            "onesignal_app_id" to "ONESIGNAL_APP_ID_DELIVERY",
            "onesignal_google_project_number" to "1080082400269"
        )
      )
    }
 
    signingConfigs {
        if (hasKeystore) {
            create("release") {
                keyAlias = keystoreProperties["keyAlias"] as String?
                keyPassword = keystoreProperties["keyPassword"] as String?
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String?
            }
        }
    }
 
    buildTypes {
    //  below code is checking if release keystore is present. - added by prateek - 03 dec 2025
    release {
 
            if (hasKeystore) {
                signingConfig = signingConfigs.getByName("release")
            } else {
                println("WARNING: Using debug signing for release because key.properties is missing!")
                signingConfig = signingConfigs.getByName("debug")
            }
 
            // Enable if you want
            // isMinifyEnabled = true
            // isShrinkResources = true
        }
    }
}
 
flutter {
    source = "../.."
}
 
// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----